WITH src AS (SELECT VISIT_ACTIVITY_KEY,
                    VISITOR_ACTIVITY_ID,
                    VISIT_KEY,
                    VISIT_ID,
                    VISITOR_KEY,
                    VISITOR_ID,
                    VISIT_ACTIVITY_START_TIMESTAMP,
                    VISIT_ACTIVITY_TYPE_NAME,
                    VISIT_DESTINATION_ID,
                    PROACTIVE_ACTION_ID,
                    PROACTIVE_ACTION_NAME,
                    PROACTIVE_ACTION_TYPE_NAME,
                    PROACTIVE_WORKFLOW_ID,
                    PROACTIVE_WORKFLOW_NAME,
                    PAGE_VIEWED_URL,
                    PAGE_VIEWED_TITLE,
                    PAGE_VIEWED_SECONDS,
                    KNOWLEDGE_BASE_ARTICLE_ID,
                    KNOWLEDGE_BASE_ARTICLE_URL,
                    KNOWLEDGE_BASE_ARTICLE_TITLE
             FROM DATAHUB.DFO_REFINED.VISIT_ACTIVITY_FACT
         MINUS
             SELECT VISIT_ACTIVITY_KEY,
                    VISITOR_ACTIVITY_ID,
                    VISIT_KEY,
                    VISIT_ID,
                    VISITOR_KEY,
                    VISITOR_ID,
                    VISIT_ACTIVITY_START_TIMESTAMP,
                    VISIT_ACTIVITY_TYPE_NAME,
                    VISIT_DESTINATION_ID,
                    PROACTIVE_ACTION_ID,
                    PROACTIVE_ACTION_NAME,
                    PROACTIVE_ACTION_TYPE_NAME,
                    PROACTIVE_WORKFLOW_ID,
                    PROACTIVE_WORKFLOW_NAME,
                    PAGE_VIEWED_URL,
                    PAGE_VIEWED_TITLE,
                    PAGE_VIEWED_SECONDS,
                    KNOWLEDGE_BASE_ARTICLE_ID,
                    KNOWLEDGE_BASE_ARTICLE_URL,
                    KNOWLEDGE_BASE_ARTICLE_TITLE
         FROM DATAHUB.DFO_REFINED.VISIT_ACTIVITY_FACT_VIEW_V001)
SELECT src.*, FALSE flag FROM src;