WITH src AS (SELECT VISIT_KEY,
                    VISIT_ID,
                    VISITOR_KEY,
                    VISIT_START_TIMESTAMP,
                    VISIT_REFERRER_URL,
                    VISIT_REFERRER_SEARCH_ENGINE,
                    VISIT_UTM_SOURCE_NAME,
                    VISIT_UTM_MEDIUM_NAME,
                    VISIT_UTM_MEDIUM_NAME,
                    VISIT_UTM_TERM_NAME,
                    VISIT_UTM_CONTENT_TEXT,
                    CHAT_OPENED_COUNT,
                    KNOWLEDGEBASE_ARTICLE_CLICKED_COUNT,
                    PROACTIVE_DISPLAYED_COUNT,
                    PROACTIVE_CLICKED_COUNT,
                    PROACTIVE_SUCCESS_COUNT,
                    PROACTIVE_FAILED_COUNT,
                    PAGE_VIEWED_COUNT,
                    PAGE_VIEWED_SECONDS,
                    CONVERSION_COUNT,
                    CONVERSION_AMOUNT,
                    CONVERSION_SECONDS
             FROM DATAHUB.DFO_REFINED.VISIT_FACT
         MINUS
             SELECT VISIT_KEY,
                    VISIT_ID,
                    VISITOR_KEY,
                    VISIT_START_TIMESTAMP,
                    VISIT_REFERRER_URL,
                    VISIT_REFERRER_SEARCH_ENGINE,
                    VISIT_UTM_SOURCE_NAME,
                    VISIT_UTM_MEDIUM_NAME,
                    VISIT_UTM_MEDIUM_NAME,
                    VISIT_UTM_TERM_NAME,
                    VISIT_UTM_CONTENT_TEXT,
                    CHAT_OPENED_COUNT,
                    KNOWLEDGEBASE_ARTICLE_CLICKED_COUNT,
                    PROACTIVE_DISPLAYED_COUNT,
                    PROACTIVE_CLICKED_COUNT,
                    PROACTIVE_SUCCESS_COUNT,
                    PROACTIVE_FAILED_COUNT,
                    PAGE_VIEWED_COUNT,
                    PAGE_VIEWED_SECONDS,
                    CONVERSION_COUNT,
                    CONVERSION_AMOUNT,
                    CONVERSION_SECONDS
         FROM DATAHUB.DFO_REFINED.VISIT_FACT_VIEW_V001)
SELECT src.*, FALSE flag FROM src;