--SELECT COLUMN_NAME, CONCAT(DATA_TYPE, '(', NUMERIC_PRECISION,',', NUMERIC_SCALE, ')') AS TYPE, IS_NULLABLE
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'VISIT_EVENT' AND DATA_TYPE = 'NUMBER' AND TYPE = 'NUMBER(38,0)'

SELECT * FROM "DATAHUB"."DFO_STRUCTURED"."VISIT_EVENT"
WHERE VISITOR_ID = 'e25e6647-9b3f-4906-8e5b-0cb1a9fbba6f'